name: vscode
description: Visual Studio Code
category: developer
logo: https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/1200px-Visual_Studio_Code_1.35_icon.svg.png
repository: staroider/vscode
