name: superset
description: A modern, enterprise-ready business intelligence web application
category: analytics
logo: https://avatars1.githubusercontent.com/u/42724554?s=400&v=4
repository: open-datastudio/superset
