name: superset
description: A modern, enterprise-ready business intelligence web application
category: analytics
logo: https://superset.incubator.apache.org/_images/s.png
repository: open-datastudio/superset
